name: Assign
on:
  issues:
    types: [opened]
jobs:
  assignme:
    name: Assign orchid00
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Assign orchid00
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign @orchid00
