name: PR
on: [pull_request]
jobs:
  commentOnPR:
    name: Comment On Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          args: comment "Thanks for your input! we will review it in the coming days!"
