name: Triage
on: [push, pull_request]
jobs:
  commentOnPushPR:
    name: Comment On Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Comment On New Issues
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "Thanks for your input! we can review it and then merge it!"
